export const dummySkillRecords: SkillRecord[] = [
	{
		id: "1",
		title: "React Basics",
		slug: "react-basics",
		description: "Introduction to React fundamentals.",
		category: "Frontend",
		tags: ["react", "javascript", "frontend"],
		installCommand: "npm install react",
		createdAt: "2026-04-23T10:00:00Z",
		authorClerkId: "user_001",
		authorEmail: "user1@example.com",
	},
	{
		id: "2",
		title: "Node.js Essentials",
		slug: "nodejs-essentials",
		description: "Core concepts of Node.js.",
		category: "Backend",
		tags: ["nodejs", "javascript", "backend"],
		installCommand: "npm install node",
		createdAt: "2026-04-23T10:05:00Z",
		authorClerkId: "user_002",
		authorEmail: "user2@example.com",
	},
	{
		id: "3",
		title: "TypeScript Mastery",
		slug: "typescript-mastery",
		description: "Advanced TypeScript techniques.",
		category: "Programming",
		tags: ["typescript", "javascript", "types"],
		installCommand: "npm install typescript",
		createdAt: "2026-04-23T10:10:00Z",
		authorClerkId: "user_003",
		authorEmail: "user3@example.com",
	},
	{
		id: "4",
		title: "CSS Grid Layout",
		slug: "css-grid-layout",
		description: "Building layouts with CSS Grid.",
		category: "Frontend",
		tags: ["css", "grid", "layout"],
		installCommand: "npm install css-grid",
		createdAt: "2026-04-23T10:15:00Z",
		authorClerkId: "user_004",
		authorEmail: "user4@example.com",
	},
	{
		id: "5",
		title: "Express API",
		slug: "express-api",
		description: "Creating REST APIs with Express.",
		category: "Backend",
		tags: ["express", "api", "nodejs"],
		installCommand: "npm install express",
		createdAt: "2026-04-23T10:20:00Z",
		authorClerkId: "user_005",
		authorEmail: "user5@example.com",
	},
];
